"""init_postgres

Revision ID: bf0e11167a9f
Revises: 
Create Date: 2026-05-23 02:33:08.432946+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0e11167a9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('prevision_principal', sa.String(), nullable=True),
    sa.Column('prevision_sub', sa.String(), nullable=True),
    sa.Column('prevision_apellido', sa.String(), nullable=True),
    sa.Column('sufijo_fonasa', sa.Boolean(), nullable=True),
    sa.Column('prevision', sa.String(), nullable=True),
    sa.Column('sintomas', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.String(), nullable=True),
    sa.Column('diagnostico_cie10', sa.String(), nullable=True),
    sa.Column('comorbilidades', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_hospitalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_cuenta_estimado', sa.Float(), nullable=True),
    sa.Column('dias_estadia', sa.Integer(), nullable=True),
    sa.Column('nivel_triage', sa.Integer(), nullable=True),
    sa.Column('categoria_solicitada', sa.String(), nullable=True),
    sa.Column('orden_hospitalizacion', sa.Boolean(), nullable=True),
    sa.Column('fecha_orden', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_clinico', sa.Boolean(), nullable=True),
    sa.Column('check_admin', sa.Boolean(), nullable=True),
    sa.Column('fecha_doble_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_asignacion_cama', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_llegada_unidad', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admision_completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_admision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pagare_firmado', sa.Boolean(), nullable=True),
    sa.Column('atencion_medica_completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_atencion_medica', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indicaciones_medicas', sa.Text(), nullable=True),
    sa.Column('prescripciones', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('contacto_emergencia', sa.String(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('medicamentos_actuales', sa.Text(), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('talla_cm', sa.Integer(), nullable=True),
    sa.Column('observaciones_clinicas', sa.Text(), nullable=True),
    sa.Column('presion_arterial', sa.String(), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('saturacion_o2', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('interconsulta_pendiente', sa.Boolean(), nullable=True),
    sa.Column('tipo_interconsultor', sa.String(), nullable=True),
    sa.Column('fecha_interconsulta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_alta', sa.String(), nullable=True),
    sa.Column('alta_probable', sa.Boolean(), nullable=True),
    sa.Column('traslado_pendiente', sa.Boolean(), nullable=True),
    sa.Column('indicacion_traslado', sa.Text(), nullable=True),
    sa.Column('unidad_traslado_destino', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_pacientes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pacientes_interconsulta_pendiente'), ['interconsulta_pendiente'], unique=False)
        batch_op.create_index(batch_op.f('ix_pacientes_orden_hospitalizacion'), ['orden_hospitalizacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_pacientes_rut'), ['rut'], unique=False)

    op.create_table('prevision_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('tarifa_dia', sa.Integer(), nullable=False),
    sa.Column('riesgo', sa.String(), nullable=False),
    sa.Column('cobertura', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prevision_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prevision_meta_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_prevision_meta_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('institucion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('datos_b64', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archivos_id'), ['id'], unique=False)

    op.create_table('camas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_camas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camas_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_camas_unidad'), ['unidad'], unique=False)

    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_id'), ['id'], unique=False)

    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('urgente', sa.Boolean(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('fecha_solicitado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_resultado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('examenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_examenes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_examenes_id'))

    op.drop_table('examenes')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_id'))

    op.drop_table('eventos')
    with op.batch_alter_table('camas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camas_unidad'))
        batch_op.drop_index(batch_op.f('ix_camas_numero'))
        batch_op.drop_index(batch_op.f('ix_camas_id'))
        batch_op.drop_index(batch_op.f('ix_camas_estado'))

    op.drop_table('camas')
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archivos_id'))

    op.drop_table('archivos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('prevision_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prevision_meta_id'))
        batch_op.drop_index(batch_op.f('ix_prevision_meta_codigo'))

    op.drop_table('prevision_meta')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_rut'))
        batch_op.drop_index(batch_op.f('ix_pacientes_orden_hospitalizacion'))
        batch_op.drop_index(batch_op.f('ix_pacientes_interconsulta_pendiente'))
        batch_op.drop_index(batch_op.f('ix_pacientes_id'))
        batch_op.drop_index(batch_op.f('ix_pacientes_estado'))

    op.drop_table('pacientes')
    # ### end Alembic commands ###
